import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { md3 } from 'vuetify/blueprints'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import { aliases, ms } from '@/plugins/icons/ms'

const lightTheme = {
  dark: false,
  colors: {
    background: '#FEF7FF',
    surface: '#FEF7FF',
    'surface-bright': '#FEF7FF',
    'surface-variant': '#E7E0EC',
    'on-surface-variant': '#49454F',
    'surface-container-lowest': '#FFFFFF',
    'surface-container-low': '#F7F2FA',
    'surface-container': '#F3EDF7',
    'surface-container-high': '#ECE6F0',
    'surface-container-highest': '#E6E0E9',
    'surface-dim': '#DED8E1',
    primary: '#6750A4',
    'on-primary': '#FFFFFF',
    'primary-container': '#EADDFF',
    'on-primary-container': '#21005D',
    secondary: '#625B71',
    'on-secondary': '#FFFFFF',
    'secondary-container': '#E8DEF8',
    'on-secondary-container': '#1D192B',
    tertiary: '#7D5260',
    'on-tertiary': '#FFFFFF',
    'tertiary-container': '#FFD8E4',
    'on-tertiary-container': '#31111D',
    error: '#B3261E',
    'on-error': '#FFFFFF',
    'error-container': '#F9DEDC',
    'on-error-container': '#410E0B',
    'on-background': '#1D1B20',
    'on-surface': '#1D1B20',
    outline: '#79747E',
    'outline-variant': '#CAC4D0',
    'inverse-surface': '#322F35',
    'on-inverse-surface': '#F5EFF7',
    'inverse-primary': '#D0BCFF',
    scrim: '#000000',
  },
}

const darkTheme = {
  dark: true,
  colors: {
    background: '#141218',
    surface: '#141218',
    'surface-bright': '#3B383E',
    'surface-variant': '#49454F',
    'on-surface-variant': '#CAC4D0',
    'surface-container-lowest': '#0F0D13',
    'surface-container-low': '#1D1B20',
    'surface-container': '#211F26',
    'surface-container-high': '#2B2930',
    'surface-container-highest': '#36343B',
    'surface-dim': '#141218',
    primary: '#D0BCFF',
    'on-primary': '#381E72',
    'primary-container': '#4F378B',
    'on-primary-container': '#EADDFF',
    secondary: '#CCC2DC',
    'on-secondary': '#332D41',
    'secondary-container': '#4A4458',
    'on-secondary-container': '#E8DEF8',
    tertiary: '#EFB8C8',
    'on-tertiary': '#492532',
    'tertiary-container': '#633B48',
    'on-tertiary-container': '#FFD8E4',
    error: '#F2B8B5',
    'on-error': '#601410',
    'error-container': '#8C1D18',
    'on-error-container': '#F9DEDC',
    'on-background': '#E6E0E9',
    'on-surface': '#E6E0E9',
    outline: '#938F99',
    'outline-variant': '#49454F',
    'inverse-surface': '#E6E0E9',
    'on-inverse-surface': '#322F35',
    'inverse-primary': '#6750A4',
    scrim: '#000000',
  },
}

export default createVuetify({
  blueprint: md3,
  components,
  directives,
  icons: {
    defaultSet: 'ms',
    aliases,
    sets: { ms },
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: lightTheme,
      dark: darkTheme,
    },
  },
  defaults: {
    VBtn: { rounded: 'pill' },
    VCard: { rounded: 'lg' },
    VTextField: { variant: 'outlined', density: 'comfortable' },
    VAutocomplete: { variant: 'outlined', density: 'comfortable' },
    VDialog: { maxWidth: 480 },
    VChip: { rounded: 'md', size: 'small' },
  },
})
